/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogPostIdRouteImport } from './routes/blog.$postId'
import { Route as ApiPostsRouteImport } from './routes/api/posts'
import { Route as ApiPostsIdRouteImport } from './routes/api/posts.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogPostIdRoute = BlogPostIdRouteImport.update({
  id: '/blog/$postId',
  path: '/blog/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPostsRoute = ApiPostsRouteImport.update({
  id: '/api/posts',
  path: '/api/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPostsIdRoute = ApiPostsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiPostsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/posts': typeof ApiPostsRouteWithChildren
  '/blog/$postId': typeof BlogPostIdRoute
  '/api/posts/$id': typeof ApiPostsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/posts': typeof ApiPostsRouteWithChildren
  '/blog/$postId': typeof BlogPostIdRoute
  '/api/posts/$id': typeof ApiPostsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/posts': typeof ApiPostsRouteWithChildren
  '/blog/$postId': typeof BlogPostIdRoute
  '/api/posts/$id': typeof ApiPostsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/posts' | '/blog/$postId' | '/api/posts/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/posts' | '/blog/$postId' | '/api/posts/$id'
  id: '__root__' | '/' | '/api/posts' | '/blog/$postId' | '/api/posts/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPostsRoute: typeof ApiPostsRouteWithChildren
  BlogPostIdRoute: typeof BlogPostIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$postId': {
      id: '/blog/$postId'
      path: '/blog/$postId'
      fullPath: '/blog/$postId'
      preLoaderRoute: typeof BlogPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/posts': {
      id: '/api/posts'
      path: '/api/posts'
      fullPath: '/api/posts'
      preLoaderRoute: typeof ApiPostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/posts/$id': {
      id: '/api/posts/$id'
      path: '/$id'
      fullPath: '/api/posts/$id'
      preLoaderRoute: typeof ApiPostsIdRouteImport
      parentRoute: typeof ApiPostsRoute
    }
  }
}

interface ApiPostsRouteChildren {
  ApiPostsIdRoute: typeof ApiPostsIdRoute
}

const ApiPostsRouteChildren: ApiPostsRouteChildren = {
  ApiPostsIdRoute: ApiPostsIdRoute,
}

const ApiPostsRouteWithChildren = ApiPostsRoute._addFileChildren(
  ApiPostsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPostsRoute: ApiPostsRouteWithChildren,
  BlogPostIdRoute: BlogPostIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
